project_name: goagentai

builds:
  - binary: goagentai
    main: ./main.go
    goos: [linux, darwin, windows]
    goarch: ["386", "amd64", "arm64"]
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64"}}CGO_ENABLED=1{{- end }}
        {{- end }}
    ignore:
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: "arm64"

archives:
  # Linux/macOS → tar.gz
  - goos: [linux, darwin]
    format: tar.gz
    files:
      - LICENSE
      - README.md
  # Windows → zip
  - goos: windows
    format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
