project_name: goagentai

builds:
  - binary: goagentai
    main: ./main.go
    goos: [linux, darwin, windows]
    goarch: ["386", "amd64", "arm64"]
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64"}}CGO_ENABLED=1{{- end }}
        {{- end }}
    ignore:
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: "arm64"


archives:
  - formats:
      - tar.gz
      - zip
    format_overrides:
      - goos: windows
        formats:
          - zip
      - goos: linux
        formats:
          - tar.gz
      - goos: darwin
          - tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
