name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release_unix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Release (Linux/macOS)
        uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: release --clean --config .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_windows:
    runs-on: windows-latest
    needs: release_unix

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build Windows
        uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: build --rm-dist --config .goreleaser.yaml
        env:
          CGO_ENABLED: 1

      - name: Upload Windows artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
