name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  # Linux + macOS build
  build_unix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build Linux/macOS artifacts
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: build --rm-dist --config .goreleaser.yaml-unix

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: unix-artifact
          path: dist/unix/*

  # Windows build
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build Windows artifacts
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: build --rm-dist --config .goreleaser.yaml-windows

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: dist/windows/*

  # Release – dopiero po obu buildach
  release:
    runs-on: ubuntu-latest
    needs: [build_unix, build_windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Unix artifact
        uses: actions/download-artifact@v4
        with:
          name: unix-artifact
          path: dist/unix

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-artifact
          path: dist/windows

      - name: Create release
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --skip-validate --skip-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
